# Generated by Django 6.0 on 2025-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Company logo for navbar (recommended size: 150x50 px, transparent PNG)', null=True, upload_to='logo/')),
            ],
        ),
    ]
