# Generated by Django 6.0 on 2025-12-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Home page hero background: Wide landscape photo, at least 1920x1080px for full-screen sharpness', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Navbar logo: Transparent PNG, recommended 180-250px wide x 50-70px tall', null=True, upload_to='logo/'),
        ),
    ]
