# Generated by Django 6.0 on 2025-12-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyinfo_hero_image_companyinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_hero_image',
            field=models.ImageField(blank=True, help_text='About page hero background - different from home', null=True, upload_to='hero/'),
        ),
    ]
